### ISSUE TITLE
filter should be strict

### ISSUE THREAD

**Issue by porosnie** [eurocontrol-swim/aixm-graph#3] opened 2020-03-25 14:19 UTC
Steps executed:
- open the 2004_v6.xml file
- select AirportHeliport
- put "ENOR" as filter by key

Result:
- 204 airports are shown with their connections, but none of them has the key "ENOR". They all have keys that start with "E" or "EN" or "ENO"

Expected result:
- only the AirportHeliport that has exactly "ENOR" in the key should ne displayed. 
- eventually, if possible to use a wildcard such as "ENO*", then all AirportHeliport that have "ENO" in the key should be displayed

Comment:
- this is applicable to all other features, not only to AirportHeliport

**Comment by antavelos** [comment] 2020-03-25 15:24
I see the problem. The problem is not the filtering (because it is implemented according to the expected result) but the fact that the filtering is initiated upon a key press. So, after hitting "ENOR" the front end is trying to handle 4 different results i.e. for "E", "EN", "ENO", "ENOR". This works fine with small amount of nodes and edges but apparently not for big ones.

I'm going to have the filtering initiated upon hitting "Enter" in order to avoid such kind of bottlenecks.

**Comment by antavelos** [comment] 2020-03-26 14:04
Done!

@porosnie Btw if you deem an issue to be resolved feel free to close it.

**Closed** 2020-04-01 15:30 UTC
